# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "487d48ddd7acab1547915d08ce84d05e"
name = "Metal Price"
handle = "metal-price-2"
application_url = "https://mpg-palace-male-indonesian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://mpg-palace-male-indonesian.trycloudflare.com/auth/callback", "https://mpg-palace-male-indonesian.trycloudflare.com/auth/shopify/callback", "https://mpg-palace-male-indonesian.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
